### ISSUE TITLE
Please explain the 5th point

### ISSUE THREAD

**Issue by venkatanirudh** [al-becker/Simple_Chatbot_SASSI#1]
Hey!! Great Work. I understood the working of python code and the dictionary file but the last point "remembering and referring to what was said before, i.e. prior to directly preceding input". Can you explain this statement on how its working in the code?
Thank you
Also couldn't find the You-I reversal questions from the code. Please guide

**Comment by al-becker** [comment]
Hey, this was just small example project for university so don't expect too much. "remembering and referring to what was said before, i.e. prior to directly preceding input" means, that the chatbot can refer to what was said in the conversation earlier. The function "def _reverse_sentence(self, sentence):" does the You-I reversal.
